### ISSUE TITLE
无法正常显示页面

### ISSUE THREAD

**Issue by MarcoChong** [wanjinzhong/WittyMonkey#8]
加载运行项目后，无法访问http://localhost:8080/toLogin.do,弹出404报错无法找到文件，请问这个问题如何解决

**Comment by wanjinzhong** [comment]
请将war包命名为ROOT.war，并放在webapps下面，如果ROOT文件夹，最好删除。然后直接启动服务器。

Thanks.

**Comment by MarcoChong** [comment]
还想请问后台管理员的账户？

**Comment by wanjinzhong** [comment]
只有商家的帐号管理，不需要后台管理员，如果需要，会在后期加入
